"use client";

import { useState } from "react";
import { Paperclip } from "lucide-react";
import { ReceiptLightbox } from "./receipt-lightbox";
import { formatINR, formatAmount } from "@/lib/format";

const SPLIT_LABEL: Record<string, string> = {
  EQUAL: "Equal",
  PERCENTAGE: "%",
  FIXED: "Fixed",
};

export type ExpenseRow = {
  id: string;
  title: string;
  total_amount: number;
  split_type: string;
  created_at: string;
  is_recurring: boolean;
  parent_expense_id: string | null;
  recurrence_rule: string | null;
  next_due_date: string | null;
  receipt_url: string | null;
  receipt_filename: string | null;
  currency: string;
  fx_rate_at_creation: number;
  payer: { id: string; name: string };
  splits: {
    id: string;
    user_id: string;
    amount: number;
    percentage: number | null;
    user: { id: string; name: string };
  }[];
  // parent title injected by page
  parentTitle?: string;
};

const CATEGORY_EMOJI: [RegExp, string][] = [
  [/rent|house|apartment|किराया/i, "🏠"],
  [/groceri|market|supermarket/i, "🛒"],
  [/electric|power|utility|bijli|eb bill/i, "⚡"],
  [/zomato|swiggy|dinner|lunch|breakfast|restaurant|pizza|food/i, "🍕"],
  [/internet|wifi|network|broadband/i, "📡"],
  [/netflix|movie|hulu|streaming|\btv\b/i, "📺"],
  [/ola|uber|taxi|cab|\bcar\b|petrol/i, "🚗"],
  [/flight|hotel|travel|airbnb/i, "✈️"],
  [/shop|amazon|mall|washing|soap|powder/i, "🛍️"],
  [/medicine|pharmacy|doctor/i, "💊"],
  [/coffee|cafe|starbucks/i, "☕"],
  [/gas cylinder|cylinder|lpg/i, "🔥"],
];

function getCategoryEmoji(title: string): string {
  for (const [re, emoji] of CATEGORY_EMOJI) {
    if (re.test(title)) return emoji;
  }
  return "🧾";
}

type Props = {
  expenses: ExpenseRow[];
  currentUserId: string;
};

function groupByMonth(expenses: ExpenseRow[]) {
  const map = new Map<string, ExpenseRow[]>();
  for (const exp of expenses) {
    const key = new Date(exp.created_at)
      .toLocaleDateString("en-IN", { month: "long", year: "numeric" })
      .toUpperCase();
    if (!map.has(key)) map.set(key, []);
    map.get(key)!.push(exp);
  }
  return map;
}

export function ExpenseList({ expenses, currentUserId }: Props) {
  const [lightbox, setLightbox] = useState<{ url: string; filename: string } | null>(null);
  const monthGroups = groupByMonth(expenses);

  return (
    <>
      <div className="space-y-8">
        {Array.from(monthGroups.entries()).map(([month, monthExpenses]) => (
          <div key={month}>
            <h3 className="mb-3 text-xs font-semibold uppercase tracking-widest text-[#6B7280]">
              {month}
            </h3>
            <ul className="space-y-3">
              {monthExpenses.map((expense) => {
                const emoji = getCategoryEmoji(expense.title);
                const isAutoGenerated = !!expense.parent_expense_id;
                const nextDueFormatted = expense.next_due_date
                  ? new Date(expense.next_due_date).toLocaleDateString("en-IN", {
                      day: "numeric",
                      month: "short",
                      year: "numeric",
                    })
                  : null;

                return (
                  <li
                    key={expense.id}
                    className="rounded-xl border border-[#E5E7EB] bg-white p-4 transition hover:shadow-sm"
                  >
                    <div className="flex flex-wrap items-start gap-3">
                      <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-[#F7F8FA] text-xl">
                        {emoji}
                      </div>

                      <div className="min-w-0 flex-1">
                        <div className="flex flex-wrap items-start justify-between gap-2">
                          <div>
                            {/* Title row with badges */}
                            <div className="flex flex-wrap items-center gap-1.5">
                              <span className="font-semibold text-[#1A1A2E]">
                                {expense.title}
                              </span>
                              {expense.is_recurring && (
                                <span
                                  title={`Recurring ${expense.recurrence_rule?.toLowerCase() ?? ""}${nextDueFormatted ? ` · Next: ${nextDueFormatted}` : " · Paused"}`}
                                  className="flex items-center gap-1 rounded-full bg-[#1B7DF0]/10 px-2 py-0.5 text-[11px] font-medium text-[#1B7DF0]"
                                >
                                  🔄{" "}
                                  {expense.recurrence_rule === "MONTHLY"
                                    ? "Monthly"
                                    : expense.recurrence_rule === "WEEKLY"
                                    ? "Weekly"
                                    : expense.recurrence_rule === "BIWEEKLY"
                                    ? "Biweekly"
                                    : expense.recurrence_rule === "YEARLY"
                                    ? "Yearly"
                                    : "Recurring"}
                                </span>
                              )}
                              {expense.receipt_url && (
                                <button
                                  onClick={() =>
                                    setLightbox({
                                      url: expense.receipt_url!,
                                      filename: expense.receipt_filename ?? "receipt",
                                    })
                                  }
                                  title="View receipt"
                                  className="flex items-center gap-0.5 rounded-full bg-[#F7F8FA] px-2 py-0.5 text-[11px] font-medium text-[#6B7280] transition hover:bg-[#E5E7EB]"
                                >
                                  <Paperclip className="h-3 w-3" />
                                  Receipt
                                </button>
                              )}
                            </div>

                            {/* Auto-generated label */}
                            {isAutoGenerated && (
                              <p className="mt-0.5 text-[11px] text-[#6B7280]">
                                Auto ·{" "}
                                {expense.parentTitle ? (
                                  <span className="italic">{expense.parentTitle}</span>
                                ) : (
                                  "generated"
                                )}
                              </p>
                            )}

                            <div className="mt-0.5 flex flex-wrap items-center gap-2 text-xs text-[#6B7280]">
                              <span>{expense.payer.name} paid</span>
                              <span>·</span>
                              <span>
                                {new Date(expense.created_at).toLocaleDateString("en-IN", {
                                  month: "short",
                                  day: "numeric",
                                })}
                              </span>
                              <span>·</span>
                              <span className="rounded bg-[#F7F8FA] px-1.5 py-0.5 font-medium">
                                {SPLIT_LABEL[expense.split_type]}
                              </span>
                            </div>
                          </div>
                          <div className="text-right">
                            <span className="text-base font-bold tabular-nums text-[#1A1A2E]">
                              {expense.currency !== "INR"
                                ? formatAmount(expense.total_amount, expense.currency)
                                : formatINR(expense.total_amount)}
                            </span>
                            {expense.currency !== "INR" && (
                              <p className="text-[11px] text-[#6B7280]">
                                ≈ {formatINR(expense.total_amount * expense.fx_rate_at_creation)}
                              </p>
                            )}
                          </div>
                        </div>

                        <div className="mt-3 grid grid-cols-2 gap-x-4 gap-y-1 sm:grid-cols-3">
                          {expense.splits.map((split) => (
                            <div
                              key={split.id}
                              className="flex items-center justify-between text-xs"
                            >
                              <span
                                className={`truncate ${
                                  split.user_id === currentUserId
                                    ? "font-semibold text-[#1B7DF0]"
                                    : "text-[#6B7280]"
                                }`}
                              >
                                {split.user.name}
                                {split.user_id === currentUserId && (
                                  <span className="ml-1 font-normal text-[#6B7280]">(you)</span>
                                )}
                              </span>
                              <span className="ml-2 shrink-0 tabular-nums text-[#1A1A2E]">
                                {expense.currency !== "INR"
                                  ? formatAmount(split.amount, expense.currency)
                                  : formatINR(split.amount)}
                                {split.percentage !== null && (
                                  <span className="ml-1 text-[#6B7280]">
                                    ({Number(split.percentage).toFixed(0)}%)
                                  </span>
                                )}
                              </span>
                            </div>
                          ))}
                        </div>
                      </div>
                    </div>
                  </li>
                );
              })}
            </ul>
          </div>
        ))}
      </div>

      {lightbox && (
        <ReceiptLightbox
          url={lightbox.url}
          filename={lightbox.filename}
          onClose={() => setLightbox(null)}
        />
      )}
    </>
  );
}
